version: "3"
services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ../conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - django
    postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/portal
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=dev
        - POSTGRES_USER=dev
        - POSTGRES_DB=dev
        - PGDATA=/var/lib/postgresql/data/portal
    django:
        build:
            context: ./../
            dockerfile: docker/Dockerfile
        image: class/django:v1
        volumes: 
            - ./../vanilla:/srv/www/vanilla
        links:
            - postgres
volumes:
    postgres_data:
